# Generated by Django 5.1 on 2024-09-19 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='created_date',
            field=models.DateField(default=datetime.date(2024, 9, 19)),
        ),
    ]
